name: Build and Publish Komet App

run-name: Build & Publish Komet App -- ${{github.ref_name}}

on:
  workflow_dispatch:
  push:
   tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
        
      - name: Checkout repository
        uses: actions/checkout@v3


      # - name: Modify docker-compose file image
      #   run:  yq -i '.services.nginx.image = "${{ secrets.DOCKER_USERNAME }}/nginx:1.26.3"' docker-compose.yml 

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker Image
        run:  docker build -t ${{ secrets.DOCKER_USERNAME }}/komet_test:${{ github.ref_name }} -f docker/Dockerfile-nginx .
          

      - name: Push docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/komet_test:${{ github.ref_name }}



 
