name: Build and Publish Komet App

on:
  workflow_dispatch:
  push:
   tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:

      - name: Checkout komet repository code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Komet Test image
        run: |
         docker build -t ${{ secrets.DOCKER_USERNAME }}/komet_test:latest -f docker/Dockerfile-komet-web .
         docker push ${{ secrets.DOCKER_USERNAME }}/komet_test:latest

      - name: Build and push Nginx image
        run: |
         docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx:latest -f docker/Dockerfile-nginx .
         docker push ${{ secrets.DOCKER_USERNAME }}/nginx:latest

      - name: Deploy with Docker Compose
        run: |
         docker-compose up -d

 
