name: Build and Publish Nginx Image

on:
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build nginx image
      run: docker-compose up --build ${{ secrets.DOCKER_USERNAME }}/nginx.

    - name: Push nginx image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/hello-world-website:latest
