name: Build and Publish Komet App

on:
  workflow_dispatch:
  push:
  #  tags:
  #     - '*'

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:

      - name: Checkout komet repository code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
         context: .
         file: docker/
         push: true
         tags: ${{ secrets.DOCKER_USERNAME }}/komet:${{ github.ref_name }}


      # - name: Build and push Docker image
      #   run: |
      #    docker build \
      #    -t ${{ secrets.DOCKER_USERNAME }}/komet:${{ github.ref_name }} \
      #    -f docker/ 



        #  docker buildx build \ 
        #  --file docker/ \ 
        #  --tag ${{ secrets.DOCKER_USERNAME }}/komet:${{ github.ref_name }} \ 
        #  --push \
        #  docker/
   
