name: Build and Publish Komet App

run-name: Build & Publish Komet App -- ${{github.ref_name}}

on:
  push:
  workflow_dispatch:
    
  #  tags:
  #     - '*'

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
        
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
         context: .
         dockerfile: docker/Dockerfile-komet-web
         push: true
         tags: ${{ secrets.DOCKER_USERNAME }}/komet:${{ github.ref_name }}



 
